version: "3"

networks:
  LEMP:

volumes: 
  mariadb:

services:
  nginx-proxy:
    container_name: LEMP_nginx_proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - LEMP

  nginx:
    restart: always
    image: nginx:stable-alpine
    container_name: LEMP_nginx
    ports:
      - "80"
    volumes:
      - ~/Desarrollo:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - LEMP
    environment:
      - VIRTUAL_HOST=dev.local

  mariaDB:
    restart: always
    image: mariadb:latest
    container_name: LEMP_mariaDB
    volumes:
      - mariadb:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    depends_on:
      - nginx
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - VIRTUAL_HOST=mariaDB
    networks:
      - LEMP

  php:
    restart: always
    image: php:7-fpm-alpine
    container_name: LEMP_php
    volumes:
      - ~/Desarrollo:/usr/share/nginx/html
    ports:
      - "9000:9000"
    networks:
      - LEMP

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: LEMP_phpMyAdmin
    ports:
      - "8183:80"
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=phpmyadmin.local
    depends_on:
      - mariaDB
    networks:
      - LEMP
    volumes:
      - /sessions

  portainer:
    restart: always
    image: portainer/portainer
    container_name: portainer
    ports: 
      - 8000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/Desarrollo/Docker/portainer_data:/data
    environment: 
      - VIRTUAL_HOST=portainer.local
    networks: 
      - LEMP

